import { useState, useEffect, useCallback } from "react";

// ─── ISLAMIC GEOMETRIC SVG PATTERN ───
const IslamicPattern = ({ opacity = 0.06, color = "#D4AF37" }) => (
  <svg width="100%" height="100%" style={{ position: "absolute", top: 0, left: 0, pointerEvents: "none", opacity }}>
    <defs>
      <pattern id="islamicGeo" x="0" y="0" width="80" height="80" patternUnits="userSpaceOnUse">
        <path d="M40 0 L80 40 L40 80 L0 40Z" fill="none" stroke={color} strokeWidth="0.5" />
        <circle cx="40" cy="40" r="16" fill="none" stroke={color} strokeWidth="0.5" />
        <path d="M20 20 L60 20 L60 60 L20 60Z" fill="none" stroke={color} strokeWidth="0.3" />
        <circle cx="40" cy="40" r="8" fill="none" stroke={color} strokeWidth="0.3" />
        <line x1="40" y1="0" x2="40" y2="80" stroke={color} strokeWidth="0.2" />
        <line x1="0" y1="40" x2="80" y2="40" stroke={color} strokeWidth="0.2" />
      </pattern>
    </defs>
    <rect width="100%" height="100%" fill="url(#islamicGeo)" />
  </svg>
);

const ArabicOrnament = () => (
  <div style={{ display: "flex", alignItems: "center", gap: 12, justifyContent: "center", margin: "8px 0" }}>
    <div style={{ width: 40, height: 1, background: "linear-gradient(90deg, transparent, #D4AF37)" }} />
    <svg width="16" height="16" viewBox="0 0 16 16"><polygon points="8,0 10,6 16,8 10,10 8,16 6,10 0,8 6,6" fill="#D4AF37" /></svg>
    <div style={{ width: 40, height: 1, background: "linear-gradient(90deg, #D4AF37, transparent)" }} />
  </div>
);

const P = {
  bg: "#0A0F1C", bgCard: "#111827", bgHover: "#1a2235", gold: "#D4AF37", goldL: "#F0D060",
  teal: "#0D7377", tealL: "#14B8A6", emerald: "#059669", text: "#E8E6E3", muted: "#9CA3AF",
  dim: "#6B7280", border: "#1E293B", success: "#22C55E", danger: "#EF4444", warn: "#F59E0B",
  purple: "#9333EA", cyan: "#06B6D4"
};

const typeColor = { lecture: P.teal, activity: P.emerald, project: P.goldL, assessment: P.warn, ctf: P.danger, ceremony: P.gold, lab: P.purple };

const CURRICULUM = [
  {
    id: "month1", month: 1, title: "Islamic Heritage in Science & Technology",
    subtitle: "Rediscovering the Roots of Modern Innovation", icon: "🕌", color: "#0D7377",
    weeks: [
      { week: 1, title: "The House of Wisdom & the Scientific Method", sessions: [
        { day: 1, title: "Welcome: Our Legacy as Vicegerents", type: "lecture", desc: "Introduction to the course. The Quranic concept of khalifah (vicegerent) and our responsibility to seek knowledge. The Prophet \u2E0F said: 'Seek knowledge from the cradle to the grave.' We explore how this duty extends to understanding AI.", objectives: ["Understand the concept of khalifah in Islam", "Connect Islamic knowledge-seeking to modern AI", "Set personal learning goals for the term"], reading: "Quran 2:30 \u2014 'I am placing a khalifah on earth'" },
        { day: 2, title: "Bayt al-Hikmah: The House of Wisdom", type: "lecture", desc: "Baghdad's House of Wisdom (9th century) was the world's greatest center of learning, where Muslim, Christian, Jewish, and Zoroastrian scholars collaborated. Caliph al-Ma'mun funded the translation of Greek, Persian, and Indian texts into Arabic, creating a knowledge revolution.", objectives: ["Describe the House of Wisdom and its purpose", "Identify how cross-cultural collaboration drove discovery", "Draw parallels to modern open-source AI communities"], reading: "Al-Khalili, 'The House of Wisdom' (excerpts)" },
        { day: 3, title: "Ibn al-Haytham & the Scientific Method", type: "activity", desc: "Ibn al-Haytham (Alhazen, 965-1040) is called the 'Father of Optics' and the 'First True Scientist.' He pioneered the scientific method \u2014 hypothesis, experimentation, observation \u2014 600 years before European scientists.", objectives: ["Explain Ibn al-Haytham's contribution to the scientific method", "Conduct a simple optics experiment", "Connect empirical methods to how AI models are trained"], activity: "Hands-on: Build a pinhole camera and discuss the empirical method" }
      ]},
      { week: 2, title: "Al-Khwarizmi: The Father of Algorithms", sessions: [
        { day: 1, title: "From Al-Khwarizmi to Algorithm", type: "lecture", desc: "Muhammad ibn Musa al-Khwarizmi (780-850 CE) was head of the House of Wisdom. The word 'algorithm' derives from the Latin transliteration of his name. His book gave us the word 'algebra.' Every AI system runs on algorithms that trace back to his work.", objectives: ["Define 'algorithm' and trace its etymology to Al-Khwarizmi", "Explain how algebra is foundational to computing", "Write a simple algorithm in pseudocode"], reading: "Al-Khwarizmi's 'Compendious Book on Calculation' (translated excerpts)" },
        { day: 2, title: "Algorithms in Everyday Life", type: "activity", desc: "Students explore how algorithms surround us: search engines, social media, GPS. We write algorithms for everyday tasks to build intuition.", objectives: ["Identify algorithms in daily technology use", "Write step-by-step algorithms for common tasks", "Understand sequencing, conditions, and loops"], activity: "Workshop: Write an algorithm for wudu (ablution) \u2014 sequencing matters!" },
        { day: 3, title: "Al-Kindi & the Birth of Cryptography", type: "lecture", desc: "Al-Kindi (801-873 CE) wrote 'On Deciphering Cryptographic Messages,' introducing frequency analysis \u2014 the first known systematic method for breaking codes. Foundational to modern cybersecurity and AI data privacy.", objectives: ["Explain frequency analysis and Al-Kindi's contribution", "Apply basic frequency analysis to decode a cipher", "Connect cryptography to modern AI security"], activity: "Mini-challenge: Decode a Caesar cipher using frequency analysis" }
      ]},
      { week: 3, title: "Islamic Innovations: Medicine, Optics & Engineering", sessions: [
        { day: 1, title: "Ibn Sina (Avicenna): Medicine & Cognition", type: "lecture", desc: "Ibn Sina (980-1037 CE) wrote 'The Canon of Medicine,' the standard medical text in Europe for 600 years. He explored cognition, distinguishing types of knowledge \u2014 foreshadowing how AI systems categorize information.", objectives: ["Describe Ibn Sina's contributions to medicine and cognitive theory", "Compare his knowledge categories to AI knowledge representation", "Discuss how AI is transforming modern healthcare"], reading: "Excerpts from The Canon of Medicine" },
        { day: 2, title: "Banu Musa & Islamic Engineering", type: "lecture", desc: "The Banu Musa brothers wrote the 'Book of Ingenious Devices' with over 100 mechanical inventions including automatic controls and feedback systems \u2014 precursors to modern robotics.", objectives: ["Identify key Islamic engineering innovations", "Explain feedback systems and their relation to AI loops", "Discuss the Islamic motivation for invention: benefit to humanity"], reading: "The Book of Ingenious Devices (selected illustrations)" },
        { day: 3, title: "Timeline Project: Islamic Innovation Map", type: "project", desc: "Students create an interactive timeline of Islamic innovations, mapping each discovery to a modern technology it influenced.", objectives: ["Research and present on an assigned Islamic scholar", "Create a visual timeline connecting past to present", "Practice collaborative research and presentation"], activity: "Group project: Islamic Innovation \u2192 Modern Tech poster" }
      ]},
      { week: 4, title: "From Automata to AI: Al-Jazari's Legacy", sessions: [
        { day: 1, title: "Al-Jazari: The Father of Robotics", type: "lecture", desc: "Ismail al-Jazari (1136-1206 CE) wrote 'The Book of Knowledge of Ingenious Mechanical Devices.' His programmable automata used camshafts, cranks, and programmable sequences. He is considered the father of robotics.", objectives: ["Describe Al-Jazari's key inventions", "Explain how programmable automata relate to modern robots", "Understand 'programmability' in machines"], reading: "Al-Jazari's Book of Knowledge (illustrated excerpts)" },
        { day: 2, title: "From Clockwork to Code", type: "activity", desc: "Trace the evolution from Al-Jazari's mechanical automata to Babbage's Analytical Engine to modern AI. Students build simple decision trees \u2014 a key AI concept.", objectives: ["Trace the lineage from mechanical to digital automation", "Build a simple decision tree for a real-world problem", "Understand that AI 'intelligence' follows programmed rules"], activity: "Build a paper decision tree: 'Should I study or rest?'" },
        { day: 3, title: "Month 1 Review & Reflection", type: "assessment", desc: "Review quiz on Islamic contributions to science and technology. Reflective journal: 'How does knowing this heritage change how I see AI?'", objectives: ["Demonstrate knowledge of key Islamic scholars and inventions", "Articulate the connection between Islamic heritage and modern AI", "Reflect personally on the responsibility of knowledge"], activity: "Quiz + Reflective journal writing + Pair sharing" }
      ]}
    ]
  },
  {
    id: "month2", month: 2, title: "AI Foundations & the Technology Stack",
    subtitle: "Understanding the Technology Shaping Our World", icon: "\uD83E\uDDE0", color: "#1A535C",
    weeks: [
      { week: 5, title: "What is AI & How the Stack Works", sessions: [
        { day: 1, title: "Defining AI: Intelligence by Design", type: "lecture", desc: "What makes something 'intelligent'? We explore AI types (narrow vs. general), current capabilities, and the Islamic perspective: only Allah creates true intelligence (aql); AI simulates patterns of reasoning.", objectives: ["Define AI and distinguish narrow from general AI", "Identify AI applications in daily life", "Understand the Islamic perspective on AI intelligence"], reading: "Quran 3:190 \u2014 'In the creation of the heavens and the earth... are signs for those of understanding'" },
        { day: 2, title: "The AI Technology Stack: Overview", type: "lecture", desc: "Every AI system sits on a technology stack \u2014 layers of hardware and software working together. We introduce the full stack: Hardware (GPUs/TPUs) \u2192 Operating System \u2192 Programming Languages (Python) \u2192 Libraries & Frameworks (PyTorch, TensorFlow) \u2192 Models \u2192 APIs & Services \u2192 Applications. Each layer supports the next, like the structure of a building.", objectives: ["Name and describe the layers of the AI technology stack", "Explain why each layer is necessary", "Compare the stack to a building: foundations, structure, facade"], reading: "Diagram handout: The AI Technology Stack" },
        { day: 3, title: "Hardware & Compute: The Physical Foundation", type: "lecture", desc: "AI requires massive computing power. GPUs and TPUs are specialized chips for the millions of mathematical operations AI needs. We explore data centers \u2014 their scale, energy consumption, and environmental impact. The Islamic principle of avoiding israaf (excess/waste) raises important questions about compute sustainability.", objectives: ["Explain why AI needs specialized hardware (GPUs/TPUs)", "Describe data centers and their role in AI", "Connect the Islamic principle of avoiding israaf to compute sustainability"], activity: "Visual exploration: Inside a data center (video + discussion)" }
      ]},
      { week: 6, title: "Programming, Frameworks & Data", sessions: [
        { day: 1, title: "Python: The Language of AI", type: "lecture", desc: "Python is the dominant language for AI/ML. We explore why: readability, vast libraries (NumPy, pandas, scikit-learn), and strong community. Students write their first lines of Python \u2014 the language that powers AI globally.", objectives: ["Explain why Python is the primary language for AI", "Write basic Python: print statements, variables, conditionals", "Understand code as a tool \u2014 intention (niyyah) determines its use"], activity: "Live coding: Your first Python program \u2014 'Bismillah, Hello AI World!'" },
        { day: 2, title: "Frameworks & Libraries: PyTorch, TensorFlow & Hugging Face", type: "lecture", desc: "AI frameworks are pre-built toolkits that simplify building models. PyTorch (Meta) and TensorFlow (Google) are the two most popular. We also explore Hugging Face, the open-source 'library' of pre-trained models available to everyone.", objectives: ["Define AI frameworks and explain their purpose", "Compare PyTorch and TensorFlow at a high level", "Explore Hugging Face as a model repository and community"], reading: "Hugging Face model library walkthrough guide" },
        { day: 3, title: "Data is the New Oil \u2014 or is it Amanah?", type: "activity", desc: "AI learns from data. We explore data types, collection methods, quality, and why 'garbage in, garbage out' applies. In Islamic ethics, personal information is an amanah (trust).", objectives: ["Define data types used in AI training", "Understand data collection, cleaning, and quality", "Apply the Islamic concept of amanah to data stewardship"], activity: "Data detective: Examine a dataset and find quality issues" }
      ]},
      { week: 7, title: "Models, APIs & Cloud Services", sessions: [
        { day: 1, title: "How AI Models Work: Training & Inference", type: "lecture", desc: "An AI model is a mathematical function learned from data. Training is the learning phase (expensive, slow); inference is the using phase (fast, cheap). Compare to learning a skill: years of practice (training) so you can perform instantly (inference).", objectives: ["Distinguish between model training and inference", "Describe the AI model lifecycle", "Understand why training is expensive and inference is cheap"], activity: "Interactive demo: Watch a model train on simple data" },
        { day: 2, title: "APIs: The Bridges of AI", type: "lecture", desc: "An API (Application Programming Interface) is how different software systems communicate. When you use ChatGPT, your browser sends requests to an API. We explore REST APIs, API keys, rate limits, and authentication.", objectives: ["Define API and explain how it connects users to AI models", "Understand request/response patterns", "Explain API keys, authentication, and rate limits"], activity: "Walkthrough: Anatomy of an API call to an AI service" },
        { day: 3, title: "Cloud vs. Local: Where AI Lives", type: "lecture", desc: "AI can run in the cloud (OpenAI, Google, AWS) or locally on your own machine. Cloud offers power but raises privacy concerns \u2014 your data leaves your device. Local AI keeps data private. For Muslims concerned about data as amanah, this distinction is critical.", objectives: ["Compare cloud-based and local AI deployment", "Identify privacy implications of each approach", "Evaluate cloud vs. local through the lens of data as amanah"], reading: "Comparison chart: Cloud AI vs. Local AI \u2014 Pros, Cons, and Islamic Considerations" }
      ]},
      { week: 8, title: "Open-Source AI & Month 2 Review", sessions: [
        { day: 1, title: "Open Source AI: Knowledge Belongs to the Ummah", type: "lecture", desc: "Open-source models (Llama, Mistral, Qwen, Gemma) are freely available. This mirrors the Islamic tradition of shared knowledge \u2014 the scholars of the House of Wisdom translated and shared freely. We explore model weights, licenses, fine-tuning, and community contributions.", objectives: ["Define open-source AI and name major open models", "Explain model weights, licenses, and fine-tuning", "Connect open-source values to Islamic knowledge-sharing traditions"], reading: "Open model comparison: Llama vs. Mistral vs. Qwen" },
        { day: 2, title: "AI Safety & Responsible Use", type: "lecture", desc: "AI safety covers: prompt injection, jailbreaking, hallucinations, misuse, and content filtering. The Islamic concept of taqwa (God-consciousness) means using technology as if Allah is watching \u2014 because He is.", objectives: ["Identify common AI safety risks", "Explain how content filters and safety guardrails work", "Apply taqwa to responsible AI usage"], activity: "Exercise: Test an AI chatbot for hallucinations" },
        { day: 3, title: "Month 2 Review & Assessment", type: "assessment", desc: "Comprehensive review of AI foundations AND the technology stack. Quiz on the full stack from hardware to applications.", objectives: ["Demonstrate understanding of the complete AI technology stack", "Explain ML, frameworks, APIs, and deployment", "Connect technical knowledge to Islamic traditions"], activity: "Quiz + Tech Stack Diagram Challenge + Group discussion" }
      ]}
    ]
  },
  {
    id: "month3", month: 3, title: "Islamic Ethics & AI Responsibility",
    subtitle: "Khalifah: Our Sacred Duty in the Age of AI", icon: "\u2696\uFE0F", color: "#4A6741",
    weeks: [
      { week: 9, title: "Khalifah: Vicegerency & Digital Stewardship", sessions: [
        { day: 1, title: "The Weight of Vicegerency", type: "lecture", desc: "Allah entrusted humanity as khalifah on earth (Quran 2:30). This trust extends to the digital realm. Muslims have a unique responsibility to ensure technology serves creation, not destroys it.", objectives: ["Define khalifah and its implications for technology", "Understand stewardship as a core Islamic responsibility", "Apply khalifah to AI development and use"], reading: "Quran 2:30, 33:72 \u2014 The trust (amanah)" },
        { day: 2, title: "Maqasid al-Shariah & Technology", type: "lecture", desc: "The Maqasid al-Shariah protect five essentials: faith, life, intellect, lineage, and wealth. How does AI impact each?", objectives: ["List and explain the five Maqasid al-Shariah", "Analyze how AI impacts each objective", "Propose safeguards aligned with Maqasid"], reading: "Al-Ghazali's classification of the Maqasid (summary)" },
        { day: 3, title: "Case Study: AI & the Five Essentials", type: "activity", desc: "Groups research how AI impacts their assigned Maqsad and present solutions grounded in Islamic ethics.", objectives: ["Research AI's impact on an assigned Maqsad", "Develop Islamic-grounded solutions", "Present findings to peers"], activity: "Group presentations: AI Impact on the Five Maqasid" }
      ]},
      { week: 10, title: "Adl (Justice) & Algorithmic Fairness", sessions: [
        { day: 1, title: "Justice in Islam, Justice in AI", type: "lecture", desc: "'O you who believe, be persistently standing firm in justice' (Quran 4:135). When AI denies loans to certain groups or targets communities, it violates adl.", objectives: ["Connect Quranic justice to algorithmic fairness", "Identify examples of algorithmic injustice", "Discuss AI accountability"], reading: "Quran 4:135, 5:8 \u2014 Standing firm for justice" },
        { day: 2, title: "Auditing Algorithms for Fairness", type: "activity", desc: "Students examine a simplified hiring algorithm, discover biases, and propose corrections.", objectives: ["Test a simplified algorithm for fairness", "Identify sources of bias", "Propose corrections"], activity: "Hands-on: Audit a mock hiring algorithm for bias" },
        { day: 3, title: "AI & Islamophobia", type: "lecture", desc: "AI content moderation disproportionately flags Arabic content. Facial recognition has surveilled Muslim communities. How do we advocate for just AI?", objectives: ["Identify how AI has impacted Muslim communities", "Discuss AI bias and Islamophobia", "Develop advocacy strategies"], reading: "Reports on AI bias against Arabic content" }
      ]},
      { week: 11, title: "Maslaha (Public Interest) & AI for Good", sessions: [
        { day: 1, title: "Maslaha: Technology for the Common Good", type: "lecture", desc: "Islamic jurisprudence uses maslaha (public benefit). AI should serve healthcare, education, disaster response, and environmental protection.", objectives: ["Define maslaha and its role in Islamic ethics", "Identify AI applications serving the common good", "Evaluate AI through the lens of maslaha"], reading: "Al-Ghazali and al-Shatibi on maslaha" },
        { day: 2, title: "AI & Environmental Stewardship", type: "lecture", desc: "'Do not cause corruption on earth' (Quran 7:56). AI consumes massive energy but can also combat climate change. Muslims must weigh these trade-offs.", objectives: ["Understand environmental cost of AI", "Identify AI for environmental protection", "Connect stewardship to Islamic principles"], reading: "Quran 7:56" },
        { day: 3, title: "Design Thinking: AI for the Ummah", type: "project", desc: "Students brainstorm AI applications for Muslim communities: Quran learning, halal verification, Islamic education, humanitarian aid.", objectives: ["Apply design thinking to community needs", "Propose a beneficial AI application", "Create a project proposal"], activity: "Design sprint: AI solution for a Muslim community need" }
      ]},
      { week: 12, title: "Privacy, Dignity & Month 3 Review", sessions: [
        { day: 1, title: "Privacy & Human Dignity in Islam", type: "lecture", desc: "'Do not spy on one another' (Quran 49:12). Islam protects privacy. AI surveillance, data harvesting, and deepfakes violate human dignity (karamah).", objectives: ["Identify Islamic texts supporting privacy", "Analyze AI threats to privacy and dignity", "Develop a personal digital privacy framework"], reading: "Quran 49:12, 24:27" },
        { day: 2, title: "Deepfakes, Misinformation & Truthfulness", type: "activity", desc: "'Be with the truthful' (Quran 9:119). Students learn to identify deepfakes and AI-generated content.", objectives: ["Identify deepfake characteristics", "Apply critical thinking to AI-generated media", "Connect sidq (truthfulness) to combating misinformation"], activity: "Deepfake detective: Spot the AI-generated content" },
        { day: 3, title: "Month 3 Review: Islamic AI Ethics Charter", type: "assessment", desc: "Students collaboratively draft an 'Islamic AI Ethics Charter' based on all values studied.", objectives: ["Synthesize all Islamic ethical principles", "Draft an Islamic AI Ethics Charter", "Present and defend ethical positions"], activity: "Group project: Draft and present the Charter" }
      ]}
    ]
  },
  {
    id: "month4", month: 4, title: "Hands-On: CTF Challenges & Local AI Lab",
    subtitle: "Practice, Build, and Protect the Digital Amanah", icon: "\uD83D\uDEA9", color: "#8B4513",
    weeks: [
      { week: 13, title: "CTF Orientation & AI Lab Setup", sessions: [
        { day: 1, title: "CTF Orientation: Rules of Engagement", type: "lecture", desc: "Introduction to CTF format, scoring, and platform. Teams formed (named after Islamic scholars).", objectives: ["Understand CTF format and rules", "Form teams", "Navigate the platform"], activity: "Platform walkthrough and team formation" },
        { day: 2, title: "Lab: Setting Up Your Local 'Ilm", type: "lab", desc: "Students install Ollama and run a local LLM. No data leaves the machine. We discuss why local AI aligns with Islamic data privacy (amanah). Step-by-step guided lab.", objectives: ["Install Ollama on a local machine", "Download and run a small open-source model", "Understand why local AI preserves privacy"], activity: "Guided lab: Install Ollama, download model, first local chat" },
        { day: 3, title: "Lab: Talking to Your Local 'Ilm Safely", type: "lab", desc: "Students explore responsible use of their local LLM. Test prompts, observe hallucinations, set system prompts for safety, create a 'Bismillah prompt' aligned with Islamic values.", objectives: ["Interact with a local LLM", "Identify hallucinations and limitations", "Create a custom Islamic values system prompt"], activity: "Lab: Test prompts, catch hallucinations, write a Bismillah system prompt" }
      ]},
      { week: 14, title: "CTF Challenges: Algorithms, Patterns & Crypto", sessions: [
        { day: 1, title: "CTF Set 1: Algorithm Puzzles", type: "ctf", desc: "Solve algorithm puzzles inspired by Al-Khwarizmi. Decode instructions, fix broken algorithms, find flags.", objectives: ["Apply algorithmic thinking", "Debug broken algorithms", "Submit first CTF flags"], activity: "CTF: Algorithm challenges" },
        { day: 2, title: "CTF Set 2: Pattern Recognition & Bias", type: "ctf", desc: "Identify patterns in data like ML models do. Spot anomalies, classify items, detect bias in datasets.", objectives: ["Apply pattern recognition", "Detect bias in datasets", "Connect data quality to AI fairness"], activity: "CTF: Pattern and bias challenges" },
        { day: 3, title: "CTF Set 3: Cryptography", type: "ctf", desc: "Honoring Al-Kindi! Decode encrypted messages using frequency analysis, substitution ciphers, and encoding schemes.", objectives: ["Apply frequency analysis", "Use decoding techniques", "Connect historical cryptography to AI security"], activity: "CTF: Cryptography challenges" }
      ]},
      { week: 15, title: "CTF Ethics, NLP & Advanced Lab", sessions: [
        { day: 1, title: "CTF Set 4: Ethics & NLP", type: "ctf", desc: "Ethical dilemmas and language processing puzzles. Apply Islamic values to find correct answers.", objectives: ["Analyze ethical AI scenarios", "Apply Islamic principles to tech decisions", "Solve NLP logic puzzles"], activity: "CTF: Ethics and NLP challenges" },
        { day: 2, title: "Lab: Fine-Tuning Behavior & RAG Concepts", type: "lab", desc: "Advanced lab: Retrieval-Augmented Generation (RAG) \u2014 feeding a local AI specific documents (like Fiqh or Quran tafsir) so it answers from trusted sources. Explore temperature, top-p, and context length parameters.", objectives: ["Understand RAG conceptually", "Adjust model parameters", "Configure a local model for Islamic texts"], activity: "Lab: Configure your local AI as an Islamic knowledge assistant" },
        { day: 3, title: "CTF Review & Strategy Session", type: "activity", desc: "Teams review progress, strategize for the final competition.", objectives: ["Review progress", "Develop team strategies", "Support peers"], activity: "Strategy session and practice round" }
      ]},
      { week: 16, title: "Capstone: Final Competition & Celebration", sessions: [
        { day: 1, title: "Final CTF Competition \u2014 Part 1", type: "ctf", desc: "Grand finale! Teams compete across all domains: algorithms, data, ethics, cryptography, NLP, Islamic knowledge.", objectives: ["Apply all skills competitively", "Collaborate under pressure", "Demonstrate comprehensive knowledge"], activity: "Timed CTF: New challenges across all domains" },
        { day: 2, title: "Final CTF Competition \u2014 Part 2 & Scores", type: "ctf", desc: "Advanced challenges. Winners earn the title 'Guardians of the Digital Amanah.'", objectives: ["Complete advanced challenges", "Demonstrate mastery", "Celebrate achievement"], activity: "Final round + Score announcement" },
        { day: 3, title: "Closing: Guardians of the Digital Amanah", type: "ceremony", desc: "Award ceremony, student presentations, closing du'a, certificates.", objectives: ["Reflect on the learning journey", "Articulate key takeaways", "Commit to being ethical stewards"], activity: "Presentations + Awards + Closing du'a + Certificates" }
      ]}
    ]
  }
];

const CTF_CHALLENGES = [
  { id: "alg1", set: 1, title: "The Khwarizmi Sequence", category: "Algorithms", difficulty: 1, points: 100, description: "Al-Khwarizmi loved sequences. Complete:\n\n2, 6, 12, 20, 30, ?\n\nFlag: FLAG{the_next_number}", hint: "Look at the differences: 4, 6, 8, 10... each increases by 2.", flag: "FLAG{42}", explanation: "Differences: 4,6,8,10,12. Next: 30+12=42." },
  { id: "alg2", set: 1, title: "The Broken Algorithm", category: "Algorithms", difficulty: 1, points: 100, description: "Bug in this algorithm:\n\nSTEP 1: width = 7\nSTEP 2: height = 5\nSTEP 3: area = width + height\nSTEP 4: Print area\n\nWhat should the area be?\nFlag: FLAG{correct_area}", hint: "Area = width x height, not +", flag: "FLAG{35}", explanation: "7 x 5 = 35, not 7 + 5 = 12." },
  { id: "alg3", set: 1, title: "The Sorting Scholar", category: "Algorithms", difficulty: 2, points: 150, description: "Sort by birth year (earliest first), take first letters:\n\nAl-Kindi (801), Ibn Sina (980), Al-Khwarizmi (780), Al-Jazari (1136), Ibn al-Haytham (965)\n\nFlag: FLAG{letters}", hint: "Sort: 780, 801, 965, 980, 1136", flag: "FLAG{AAIIA}", explanation: "Al-Khwarizmi, Al-Kindi, Ibn al-Haytham, Ibn Sina, Al-Jazari = AAIIA" },
  { id: "pat1", set: 2, title: "The Data Detective", category: "Pattern Recognition", difficulty: 1, points: 100, description: "AI classifies fruits:\nRound+Red+Sweet=Apple\nRound+Orange+Sweet=Orange\nOval+Yellow+Sour=Lemon\n\nOval+Green+Sour=???\nFlag: FLAG{fruit_lowercase}", hint: "Common oval, green, sour fruit...", flag: "FLAG{lime}", explanation: "Oval+green+sour = lime." },
  { id: "pat2", set: 2, title: "The Anomaly Spotter", category: "Pattern Recognition", difficulty: 2, points: 150, description: "Fajr times (should decrease ~2min/day):\nDay1:5:30 Day2:5:28 Day3:5:26 Day4:5:24\nDay5:6:22 Day6:5:20 Day7:5:18\n\nWhich day has the error?\nFlag: FLAG{day_number}", hint: "One day jumps up a whole hour!", flag: "FLAG{5}", explanation: "Day 5 shows 6:22 instead of ~5:22." },
  { id: "bias1", set: 3, title: "The Unfair Filter", category: "Bias Detection", difficulty: 2, points: 150, description: "AI flagged:\n1. 'Destroy this exam!' = Violent\n2. 'Sunset was killer' = OK\n3. 'Allahu Akbar, beautiful day' = Extremist\n4. 'Pizza is fire' = OK\n\nWhich shows religious bias?\nFlag: FLAG{number}", hint: "'Allahu Akbar' means 'God is Greatest' - said in daily prayer...", flag: "FLAG{3}", explanation: "Flagging 'Allahu Akbar' as extremist is clear religious bias." },
  { id: "crypto1", set: 4, title: "Al-Kindi's Cipher", category: "Cryptography", difficulty: 1, points: 100, description: "Caesar cipher (shift 3):\nNQRZOHGJH LV OLJKW\n\nFlag: FLAG{decoded_no_spaces}", hint: "Shift each letter back by 3: N->K, Q->N...", flag: "FLAG{KNOWLEDGEISLIGHT}", explanation: "KNOWLEDGE IS LIGHT" },
  { id: "crypto2", set: 4, title: "The Frequency Detective", category: "Cryptography", difficulty: 2, points: 200, description: "Most common letter in English = E.\nIn this text, most common = X.\n\nXVX DKFX YHX VRLSQD\n\nIf X=E, decode it.\nFlag: FLAG{decoded_no_spaces}", hint: "E=5, X=24. Shift=19. Shift back 19.", flag: "FLAG{EVERYONEISEQUAL}", explanation: "EVERYONE IS EQUAL - a core Islamic value!" },
  { id: "ethics1", set: 5, title: "The Maqasid Challenge", category: "Ethics", difficulty: 2, points: 150, description: "Match scenario to Maqsad:\nA) Deepfake false teachings\nB) Mosque surveillance\nC) Medical misdiagnosis\nD) Elderly scam\n\n1=Faith 2=Life 3=Wealth 5=Privacy\nFlag: FLAG{A B C D as numbers}", hint: "false religion=faith, surveillance=privacy, misdiagnosis=life, scam=wealth", flag: "FLAG{1523}", explanation: "A=1(Faith), B=5(Privacy), C=2(Life), D=3(Wealth)" },
  { id: "nlp1", set: 6, title: "Sentiment Decoder", category: "NLP", difficulty: 1, points: 100, description: "AI classified:\n1. 'Love the mosque!' = Positive\n2. 'Traffic terrible' = Negative\n3. 'Exam not difficult' = Negative (?)\n4. 'Alhamdulillah' = Positive\n\nWhich is wrong?\nFlag: FLAG{number}", hint: "AI struggles with negation: 'not difficult' = positive", flag: "FLAG{3}", explanation: "'Not difficult at all' is positive. AI confused by negation." }
];

const LAB_STEPS = [
  { id: 1, title: "Understanding Local AI", icon: "\uD83E\uDDE0", content: "Before we begin, let's understand what we're building. A **Local LLM** (Large Language Model) is an AI that runs entirely on YOUR computer. Unlike cloud services like ChatGPT or Gemini, your conversations never leave your machine.\n\n**Why does this matter Islamically?**\nPersonal data is an **amanah** (trust). When you use cloud AI, your questions, documents, and personal information are sent to external servers. A local AI keeps your data private \u2014 fulfilling the Islamic obligation of protecting the trust others place in you.\n\nThe Prophet said: *'There is no faith for one who has no trustworthiness.'* (Ahmad)\n\n**What is Ollama?**\nOllama is a free, open-source tool that makes running AI models on your own computer simple. It handles downloading models, managing memory, and providing a clean interface \u2014 all locally.", prereqs: ["A computer with at least 8GB RAM (16GB recommended)", "macOS, Windows, or Linux operating system", "At least 5GB free disk space", "Administrator/sudo access to install software"] },
  { id: 2, title: "Installing Ollama", icon: "\u2B07\uFE0F", content: "Ollama is available for all major operating systems. Choose your platform below and follow the instructions.", commands: [
    { platform: "macOS", steps: ["Visit https://ollama.com and click 'Download for macOS'", "Open the downloaded .dmg file", "Drag Ollama to your Applications folder", "Open Ollama from Applications", "Open Terminal (Applications > Utilities > Terminal)"] },
    { platform: "Windows", steps: ["Visit https://ollama.com and click 'Download for Windows'", "Run the downloaded installer (.exe)", "Follow the installation wizard", "Ollama starts automatically in system tray", "Open Command Prompt or PowerShell"] },
    { platform: "Linux", steps: ["Open your terminal", "Run: curl -fsSL https://ollama.com/install.sh | sh", "Wait for installation to complete", "The ollama service starts automatically"] }
  ], verify: "ollama --version", verifyDesc: "You should see a version number like 'ollama version 0.5.x'" },
  { id: 3, title: "Downloading Your First Model", icon: "\uD83D\uDCE6", content: "Now we'll download an AI model to run locally.\n\n**Recommended starter models:**\n\u2022 **qwen2.5:1.5b** \u2014 Very small (1GB), fast, good for learning\n\u2022 **llama3.2:3b** \u2014 Small (2GB), more capable\n\u2022 **phi4-mini** \u2014 Small (2.5GB), strong reasoning\n\n**Important Islamic Note:** These models were trained on internet data. They may produce inaccurate Islamic information. Always verify with qualified scholars.", mainCommand: "ollama pull qwen2.5:1.5b", mainCommandDesc: "Downloads the Qwen 2.5 1.5B model (~1GB). May take 5-15 minutes.", altCommands: [
    { cmd: "ollama pull llama3.2:3b", desc: "Alternative: Llama 3.2 3B (larger, more capable)" },
    { cmd: "ollama list", desc: "Check which models you have downloaded" }
  ]},
  { id: 4, title: "Running Your First Conversation", icon: "\uD83D\uDCAC", content: "Bismillah \u2014 let's talk to your local AI!\n\nThis is a historic moment: you are running AI entirely on your own hardware. No data leaves your machine. You are in full control.", mainCommand: "ollama run qwen2.5:1.5b", mainCommandDesc: "Opens an interactive chat. Type messages and press Enter.", examplePrompts: [
    { prompt: "What is the significance of the House of Wisdom in Baghdad?", purpose: "Test Islamic history knowledge" },
    { prompt: "Explain what an algorithm is in simple terms.", purpose: "Test AI concept explanation" },
    { prompt: "What are the five Maqasid al-Shariah?", purpose: "Test Islamic knowledge (verify with scholars!)" },
    { prompt: "Write a Python function that adds two numbers.", purpose: "Test coding ability" }
  ], exitCommand: "/bye", exitDesc: "Type /bye to exit the chat." },
  { id: 5, title: "Catching Hallucinations", icon: "\uD83D\uDC41\uFE0F", content: "AI models sometimes **hallucinate** \u2014 they generate confident but incorrect information. Especially dangerous with Islamic knowledge.\n\n**Why do hallucinations happen?**\nModels predict the most likely next word. They don't 'know' truth from fiction.\n\n**Test for hallucinations:**\n1. *'What surah comes after Al-Fatiha?'* (Al-Baqarah)\n2. *'How many rakahs in Fajr?'* (2 fard)\n3. *'Who wrote Sahih al-Bukhari?'* (Imam al-Bukhari)\n4. *'Date of the Battle of Badr?'* (17 Ramadan 2 AH / 624 CE)\n\nThe Quran warns: *'Do not pursue that of which you have no knowledge.'* (17:36)", activity: "Test your local AI with 5 factual questions. Record which are hallucinations." },
  { id: 6, title: "Creating a Bismillah System Prompt", icon: "\uD83D\uDCDC", content: "A **system prompt** shapes how an AI model behaves. It's the AI's job description and moral compass.\n\nWe'll create one aligned with Islamic values.", mainCommand: "ollama run qwen2.5:1.5b --system \"You are a helpful, honest assistant. Principles: 1) Always be truthful. If unsure, say so. 2) Never fabricate Islamic rulings. Remind users to verify with scholars. 3) Be respectful of all people and faiths. 4) Avoid harmful content. 5) Present balanced perspectives. 6) Accuracy over confidence.\"", mainCommandDesc: "Starts the model with your Islamic values system prompt.", customization: "Customize your prompt! Ideas:\n\u2022 Add: 'Respond suitably for high school students'\n\u2022 Add: 'Reference Islamic principles for AI ethics'\n\u2022 Add: 'If asked to generate haram content, politely decline'\n\nSave to a file for reuse:\necho 'Your prompt' > my_system_prompt.txt\nollama run qwen2.5:1.5b --system \"$(cat my_system_prompt.txt)\"" },
  { id: 7, title: "Model Parameters & Safety", icon: "\u2699\uFE0F", content: "AI models have **parameters** that control behavior.\n\n**Key Parameters:**\n\n**Temperature** (0.0 - 2.0)\nControls randomness/creativity.\n\u2022 0.0-0.3 = Focused, factual (best for Islamic Q&A)\n\u2022 0.7-1.0 = Balanced\n\u2022 1.0-2.0 = Very creative (risky for facts)\n\n**Top-P** (0.0 - 1.0)\nControls diversity of word choices.\n\n**Context Length**\nHow much conversation history the model remembers.\n\n**Safety:** For Islamic knowledge queries, use LOW temperature (0.1-0.3). Accuracy, not creativity, for deen.", mainCommand: "ollama run qwen2.5:1.5b --system \"Be accurate and factual.\" --keepalive 5m", mainCommandDesc: "--keepalive keeps model loaded for faster responses.", configExample: "# Create a Modelfile:\nFROM qwen2.5:1.5b\nSYSTEM \"Helpful Islamic studies assistant. Be accurate. Say when unsure.\"\nPARAMETER temperature 0.3\nPARAMETER top_p 0.9\n\n# Build and run:\n# ollama create my-ilm-assistant -f Modelfile\n# ollama run my-ilm-assistant" },
  { id: 8, title: "Graduation: Your Local 'Ilm is Ready", icon: "\uD83C\uDF93", content: "MashaAllah! You have successfully:\n\n\u2705 Installed Ollama on your machine\n\u2705 Downloaded and run an open-source AI model\n\u2705 Had your first local AI conversation\n\u2705 Tested for and identified hallucinations\n\u2705 Created a Bismillah system prompt\n\u2705 Learned about parameters and safety\n\u2705 Configured a custom AI assistant\n\n**You are now a Guardian of the Digital Amanah.**\n\nUse your local AI with taqwa, verify its outputs, and remember that true 'ilm comes from Allah alone \u2014 AI is merely a tool.\n\n**Next steps:**\n\u2022 Try larger models (llama3.1:8b, qwen2.5:7b)\n\u2022 Explore Ollama's API for building apps\n\u2022 Research RAG for feeding documents to your AI\n\u2022 Join the Muslim AI ethics community", isGraduation: true }
];

export default function App() {
  const [view, setView] = useState("home");
  const [selMonth, setSelMonth] = useState(null);
  const [selSession, setSelSession] = useState(null);
  const [selWeek, setSelWeek] = useState(null);
  const [ctfScore, setCtfScore] = useState(0);
  const [doneCh, setDoneCh] = useState({});
  const [doneS, setDoneS] = useState({});
  const [selCh, setSelCh] = useState(null);
  const [ctfIn, setCtfIn] = useState("");
  const [ctfRes, setCtfRes] = useState(null);
  const [hint, setHint] = useState(false);
  const [sb, setSb] = useState(false);
  const [an, setAn] = useState(false);
  const [labSt, setLabSt] = useState(0);
  const [labD, setLabD] = useState({});
  const [cp, setCp] = useState(null);

  useEffect(() => { setAn(false); const t = setTimeout(() => setAn(true), 50); return () => clearTimeout(t); }, [view, selMonth, selSession, selCh, labSt]);

  const totS = CURRICULUM.reduce((t, m) => t + m.weeks.reduce((w, wk) => w + wk.sessions.length, 0), 0);
  const dC = Object.keys(doneS).length;
  const pct = Math.round((dC / totS) * 100);
  const totPts = CTF_CHALLENGES.reduce((t, c) => t + c.points, 0);

  const nav = useCallback((v, d = {}) => {
    setView(v); if (d.month !== undefined) setSelMonth(d.month); if (d.session !== undefined) setSelSession(d.session);
    if (d.week !== undefined) setSelWeek(d.week);
    if (d.challenge !== undefined) { setSelCh(d.challenge); setCtfIn(""); setCtfRes(null); setHint(false); }
    if (d.labStep !== undefined) setLabSt(d.labStep);
    setSb(false); window.scrollTo(0, 0);
  }, []);

  const togS = useCallback((sid) => setDoneS(p => { const n = { ...p }; n[sid] ? delete n[sid] : n[sid] = true; return n; }), []);

  const subFlag = useCallback(() => {
    const ch = CTF_CHALLENGES.find(c => c.id === selCh); if (!ch) return;
    if (ctfIn.trim().toUpperCase() === ch.flag.toUpperCase()) {
      setCtfRes("ok"); if (!doneCh[ch.id]) { setDoneCh(p => ({ ...p, [ch.id]: true })); setCtfScore(p => p + ch.points); }
    } else setCtfRes("no");
  }, [selCh, ctfIn, doneCh]);

  const cpy = (t) => { navigator.clipboard?.writeText(t).then(() => { setCp(t); setTimeout(() => setCp(null), 2000); }); };

  const Bd = ({ children, color = P.gold }) => (<span style={{ display: "inline-block", padding: "2px 10px", borderRadius: 20, fontSize: 11, fontWeight: 600, background: color + "22", color, border: `1px solid ${color}44`, letterSpacing: 0.5, textTransform: "uppercase" }}>{children}</span>);
  const Bk = ({ onClick, label = "Back" }) => (<button onClick={onClick} style={{ background: "none", border: "none", color: P.gold, cursor: "pointer", fontFamily: "Outfit", fontSize: 14, fontWeight: 500, display: "flex", alignItems: "center", gap: 6, padding: "8px 0", marginBottom: 16 }}>{"\u2190"} {label}</button>);
  const Br = ({ value, max, h = 6, color = P.tealL }) => (<div style={{ width: "100%", height: h, background: P.border, borderRadius: h / 2, overflow: "hidden" }}><div style={{ width: `${Math.min((value / max) * 100, 100)}%`, height: "100%", background: `linear-gradient(90deg, ${color}, ${P.gold})`, borderRadius: h / 2, transition: "width 0.6s ease" }} /></div>);
  const CB = ({ children }) => (<div style={{ position: "relative", background: "#000", border: `1px solid ${P.border}`, borderRadius: 8, padding: "14px 16px", paddingRight: 70, fontFamily: "monospace", fontSize: 13, color: "#4ADE80", lineHeight: 1.6, overflowX: "auto", margin: "8px 0", whiteSpace: "pre-wrap", wordBreak: "break-all" }}><button onClick={() => cpy(children)} style={{ position: "absolute", top: 8, right: 8, background: P.border, border: "none", borderRadius: 4, padding: "4px 10px", color: cp === children ? P.success : P.muted, fontSize: 11, cursor: "pointer", fontFamily: "Outfit" }}>{cp === children ? "Copied!" : "Copy"}</button>{children}</div>);
  const aS = { opacity: an ? 1 : 0, transform: an ? "translateY(0)" : "translateY(20px)", transition: "all 0.5s ease" };
  const catCol = { Algorithms: P.teal, "Pattern Recognition": P.emerald, "Bias Detection": P.warn, Cryptography: P.purple, Ethics: P.gold, NLP: P.tealL };

  const renderMd = (text) => text.split("\n").map((line, i) => {
    if (!line.trim()) return <br key={i} />;
    const parts = line.split(/(\*\*[^*]+\*\*)/g).map((p, j) => p.startsWith("**") && p.endsWith("**") ? <strong key={j} style={{ color: P.gold }}>{p.slice(2, -2)}</strong> : p);
    const parts2 = []; parts.forEach(p => { if (typeof p === "string") { p.split(/(\*[^*]+\*)/g).forEach((q, k) => { parts2.push(q.startsWith("*") && q.endsWith("*") && !q.startsWith("**") ? <em key={`i${k}`} style={{ color: P.muted }}>{q.slice(1, -1)}</em> : q); }); } else parts2.push(p); });
    return <p key={i} style={{ fontFamily: "Outfit", fontSize: 14, color: P.text, lineHeight: 1.7, margin: "0 0 6px" }}>{parts2}</p>;
  });

  const Header = () => (<header style={{ position: "sticky", top: 0, zIndex: 100, background: P.bg + "ee", backdropFilter: "blur(12px)", borderBottom: `1px solid ${P.border}`, padding: "12px 20px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
    <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
      <button onClick={() => setSb(!sb)} style={{ background: "none", border: "none", color: P.gold, fontSize: 22, cursor: "pointer", padding: 4 }}>{"\u2630"}</button>
      <div onClick={() => nav("home")} style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: 8 }}>
        <span style={{ fontSize: 22 }}>{"\u262A"}</span>
        <div><div style={{ fontFamily: "Amiri", fontSize: 17, color: P.gold, lineHeight: 1.1 }}>AI and Islamic Ethics</div><div style={{ fontFamily: "Outfit", fontSize: 9, color: P.dim, letterSpacing: 1.5, textTransform: "uppercase" }}>Guardians of the Digital Amanah</div></div>
      </div>
    </div>
    <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
      <div style={{ textAlign: "right" }}><div style={{ fontSize: 10, color: P.dim, fontFamily: "Outfit" }}>CTF</div><div style={{ fontSize: 15, fontWeight: 700, color: P.gold, fontFamily: "Outfit" }}>{ctfScore}</div></div>
      <div style={{ width: 34, height: 34, borderRadius: "50%", background: `linear-gradient(135deg, ${P.teal}, ${P.gold})`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, color: P.bg, fontFamily: "Outfit" }}>{pct}%</div>
    </div>
  </header>);

  const Sidebar = () => (<div style={{ position: "fixed", top: 0, left: sb ? 0 : -280, width: 280, height: "100vh", background: P.bgCard, borderRight: `1px solid ${P.border}`, zIndex: 1000, transition: "left 0.3s ease", overflowY: "auto", padding: "24px 0" }}>
    <div style={{ padding: "0 20px 20px", borderBottom: `1px solid ${P.border}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontFamily: "Amiri", fontSize: 18, color: P.gold }}>{"\u262A"} Navigation</span><button onClick={() => setSb(false)} style={{ background: "none", border: "none", color: P.muted, fontSize: 24, cursor: "pointer" }}>{"\u00D7"}</button></div>
    {[{ l: "Home", i: "\uD83C\uDFE0", v: "home" }, { l: "Curriculum", i: "\uD83D\uDCDA", v: "curriculum" }, { l: "CTF Challenges", i: "\uD83D\uDEA9", v: "ctf" }, { l: "Local AI Lab", i: "\uD83D\uDD2C", v: "lab" }, { l: "Progress", i: "\uD83D\uDCCA", v: "progress" }].map(x => (
      <button key={x.v} onClick={() => nav(x.v)} style={{ display: "flex", alignItems: "center", gap: 12, width: "100%", padding: "14px 20px", background: view === x.v ? P.gold + "15" : "transparent", border: "none", borderLeft: view === x.v ? `3px solid ${P.gold}` : "3px solid transparent", color: view === x.v ? P.gold : P.text, fontFamily: "Outfit", fontSize: 15, cursor: "pointer", textAlign: "left" }}><span style={{ fontSize: 18 }}>{x.i}</span>{x.l}</button>
    ))}
    <div style={{ padding: 20, marginTop: 20, borderTop: `1px solid ${P.border}` }}>
      <div style={{ fontSize: 12, color: P.dim, marginBottom: 8, fontFamily: "Outfit" }}>PROGRESS</div><Br value={dC} max={totS} h={8} /><div style={{ fontSize: 13, color: P.muted, marginTop: 6, fontFamily: "Outfit" }}>{dC}/{totS} sessions</div>
      <div style={{ fontSize: 12, color: P.dim, marginBottom: 8, marginTop: 16, fontFamily: "Outfit" }}>CTF SCORE</div><div style={{ fontSize: 22, fontWeight: 700, color: P.gold, fontFamily: "Outfit" }}>{ctfScore}<span style={{ fontSize: 13, color: P.dim }}>/{totPts}</span></div>
      <div style={{ fontSize: 12, color: P.dim, marginBottom: 8, marginTop: 16, fontFamily: "Outfit" }}>LAB</div><Br value={Object.keys(labD).length} max={LAB_STEPS.length} h={8} color={P.purple} /><div style={{ fontSize: 13, color: P.muted, marginTop: 6, fontFamily: "Outfit" }}>{Object.keys(labD).length}/{LAB_STEPS.length} steps</div>
    </div>
  </div>);

  const Home = () => (<div style={aS}>
    <div style={{ position: "relative", padding: "52px 24px 44px", textAlign: "center", overflow: "hidden", background: `linear-gradient(180deg, ${P.bg}, #0D1B2A)` }}><IslamicPattern opacity={0.08} /><div style={{ position: "relative", zIndex: 1 }}>
      <div style={{ fontFamily: "Amiri", fontSize: 44, color: P.gold, lineHeight: 1.1, marginBottom: 4 }}>{"\u0628\u0650\u0633\u0652\u0645\u0650 \u0671\u0644\u0644\u0651\u064E\u0670\u0647\u0650"}</div>
      <div style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim, letterSpacing: 2.5, textTransform: "uppercase", marginBottom: 20 }}>In the Name of Allah, the Most Gracious, the Most Merciful</div>
      <h1 style={{ fontFamily: "Amiri", fontSize: 34, color: P.text, fontWeight: 700, margin: 0, lineHeight: 1.2 }}>AI <span style={{ color: P.gold }}>and Islamic Ethics</span></h1>
      <p style={{ fontFamily: "Outfit", fontSize: 15, color: P.muted, maxWidth: 560, margin: "14px auto 0", lineHeight: 1.6, fontWeight: 300 }}>A one-term curriculum for Muslim high school students: Islamic contributions to science, AI foundations & tech stack, ethics, CTF challenges, and building your own local AI.</p>
      <ArabicOrnament />
      <div style={{ display: "flex", gap: 10, justifyContent: "center", marginTop: 20, flexWrap: "wrap" }}>
        <button onClick={() => nav("curriculum")} style={{ padding: "11px 24px", background: `linear-gradient(135deg, ${P.gold}, #B8962E)`, color: P.bg, border: "none", borderRadius: 8, fontFamily: "Outfit", fontSize: 14, fontWeight: 600, cursor: "pointer" }}>Begin Journey {"\u2192"}</button>
        <button onClick={() => nav("lab")} style={{ padding: "11px 24px", background: "transparent", color: P.purple, border: `1.5px solid ${P.purple}55`, borderRadius: 8, fontFamily: "Outfit", fontSize: 14, fontWeight: 500, cursor: "pointer" }}>{"\uD83D\uDD2C"} Local AI Lab</button>
        <button onClick={() => nav("ctf")} style={{ padding: "11px 24px", background: "transparent", color: P.gold, border: `1.5px solid ${P.gold}55`, borderRadius: 8, fontFamily: "Outfit", fontSize: 14, fontWeight: 500, cursor: "pointer" }}>{"\uD83D\uDEA9"} CTF</button>
      </div>
    </div></div>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 1, background: P.border }}>{[{ l: "Months", v: "4", i: "\uD83D\uDCC5" }, { l: "Sessions", v: "48", i: "\uD83D\uDCD6" }, { l: "CTF", v: "10", i: "\uD83D\uDEA9" }, { l: "Lab Steps", v: "8", i: "\uD83D\uDD2C" }, { l: "Hours", v: "24", i: "\u23F1" }].map(s => (<div key={s.l} style={{ background: P.bgCard, padding: "14px 8px", textAlign: "center" }}><div style={{ fontSize: 20 }}>{s.i}</div><div style={{ fontFamily: "Outfit", fontSize: 22, fontWeight: 700, color: P.text }}>{s.v}</div><div style={{ fontFamily: "Outfit", fontSize: 10, color: P.dim, textTransform: "uppercase", letterSpacing: 0.8 }}>{s.l}</div></div>))}</div>
    <div style={{ padding: "28px 24px" }}><h2 style={{ fontFamily: "Amiri", fontSize: 24, color: P.text, marginBottom: 4 }}>The Four Pillars</h2><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.dim, marginBottom: 20 }}>Your journey through 4 months</p>
    {CURRICULUM.map((m, i) => { const ms = m.weeks.reduce((t, w) => t + w.sessions.length, 0); const md = m.weeks.reduce((t, w) => t + w.sessions.filter(s => doneS[`${m.id}-w${w.week}-d${s.day}`]).length, 0); return (
      <div key={m.id} onClick={() => nav("month", { month: i })} style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", cursor: "pointer", borderLeft: `4px solid ${m.color}`, marginBottom: 12 }} onMouseOver={e => e.currentTarget.style.background = P.bgHover} onMouseOut={e => e.currentTarget.style.background = P.bgCard}>
        <div style={{ display: "flex", alignItems: "flex-start", gap: 14 }}><div style={{ fontSize: 32, flexShrink: 0 }}>{m.icon}</div><div style={{ flex: 1 }}><div style={{ fontFamily: "Outfit", fontSize: 11, fontWeight: 600, color: m.color, letterSpacing: 1.5, textTransform: "uppercase" }}>Month {m.month}</div><h3 style={{ fontFamily: "Amiri", fontSize: 19, color: P.text, margin: "0 0 3px" }}>{m.title}</h3><p style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim, margin: "0 0 10px" }}>{m.subtitle}</p><Br value={md} max={ms} h={5} color={m.color} /><div style={{ fontFamily: "Outfit", fontSize: 11, color: P.muted, marginTop: 3 }}>{md}/{ms} sessions</div></div><span style={{ color: P.dim, fontSize: 18 }}>{"\u2192"}</span></div>
      </div>); })}
    </div>
    <div style={{ padding: "0 24px 28px" }}><div onClick={() => nav("lab")} style={{ background: `linear-gradient(135deg, ${P.purple}12, ${P.cyan}08)`, border: `1px solid ${P.purple}33`, borderRadius: 12, padding: "24px", cursor: "pointer" }} onMouseOver={e => e.currentTarget.style.borderColor = P.purple + "66"} onMouseOut={e => e.currentTarget.style.borderColor = P.purple + "33"}>
      <div style={{ display: "flex", alignItems: "center", gap: 14 }}><div style={{ fontSize: 36 }}>{"\uD83D\uDD2C"}</div><div style={{ flex: 1 }}><div style={{ fontFamily: "Outfit", fontSize: 11, fontWeight: 600, color: P.purple, letterSpacing: 1.5, textTransform: "uppercase" }}>Interactive Lab</div><h3 style={{ fontFamily: "Amiri", fontSize: 20, color: P.text, margin: "2px 0" }}>Build Your Own Local {"\u02BF"}Ilm</h3><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.dim, margin: "0 0 8px" }}>Step-by-step guide to running AI privately on your machine using Ollama.</p><Br value={Object.keys(labD).length} max={LAB_STEPS.length} h={5} color={P.purple} /><span style={{ fontFamily: "Outfit", fontSize: 11, color: P.muted }}>{Object.keys(labD).length}/{LAB_STEPS.length} steps</span></div><span style={{ color: P.purple }}>{"\u2192"}</span></div>
    </div></div>
    <div style={{ padding: "0 24px 32px", textAlign: "center" }}><div style={{ background: `linear-gradient(135deg, ${P.gold}0A, ${P.teal}0A)`, border: `1px solid ${P.gold}22`, borderRadius: 16, padding: "28px 24px" }}><div style={{ fontFamily: "Amiri", fontSize: 26, color: P.gold, marginBottom: 10, lineHeight: 1.4 }}>{"\u0671\u0642\u0652\u0631\u064E\u0623\u0652 \u0628\u0650\u0671\u0633\u0652\u0645\u0650 \u0631\u064E\u0628\u0651\u0650\u0643\u064E \u0671\u0644\u0651\u064E\u0630\u0650\u0649 \u062E\u064E\u0644\u064E\u0642\u064E"}</div><p style={{ fontFamily: "Outfit", fontSize: 14, color: P.muted, fontStyle: "italic", margin: 0 }}>"Read! In the name of your Lord who created." {"\u2014"} Quran 96:1</p></div></div>
  </div>);

  const CurrV = () => (<div style={{ padding: "24px", ...aS }}><h2 style={{ fontFamily: "Amiri", fontSize: 26, color: P.text, margin: "0 0 4px" }}>Full Curriculum</h2><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.dim, marginBottom: 8 }}>4 months {"\u00B7"} 3/week {"\u00B7"} 30 min {"\u00B7"} 48 sessions</p><Br value={dC} max={totS} h={8} /><div style={{ fontFamily: "Outfit", fontSize: 12, color: P.muted, margin: "4px 0 20px" }}>{pct}% complete</div>
    {CURRICULUM.map((m, mi) => (<div key={m.id} style={{ marginBottom: 28 }}>
      <div onClick={() => nav("month", { month: mi })} style={{ display: "flex", alignItems: "center", gap: 12, padding: "14px", background: m.color + "15", border: `1px solid ${m.color}33`, borderRadius: 10, cursor: "pointer", marginBottom: 10 }}><span style={{ fontSize: 26 }}>{m.icon}</span><div><div style={{ fontFamily: "Outfit", fontSize: 10, fontWeight: 600, color: m.color, letterSpacing: 1, textTransform: "uppercase" }}>Month {m.month}</div><div style={{ fontFamily: "Amiri", fontSize: 18, color: P.text }}>{m.title}</div></div><span style={{ marginLeft: "auto", color: m.color }}>{"\u2192"}</span></div>
      {m.weeks.map(w => (<div key={w.week} style={{ marginLeft: 14, marginBottom: 6 }}><div style={{ fontFamily: "Outfit", fontSize: 12, fontWeight: 600, color: P.muted, padding: "6px 0", display: "flex", alignItems: "center", gap: 6 }}><div style={{ width: 5, height: 5, borderRadius: 3, background: m.color }} />Week {w.week}: {w.title}</div>
        {w.sessions.map(s => { const sid = `${m.id}-w${w.week}-d${s.day}`; const dn = doneS[sid]; return (<div key={sid} onClick={() => nav("session", { month: mi, week: w.week, session: s })} style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 10px", marginLeft: 12, borderLeft: `2px solid ${P.border}`, cursor: "pointer" }} onMouseOver={e => e.currentTarget.style.background = P.bgHover} onMouseOut={e => e.currentTarget.style.background = "transparent"}>
          <div onClick={e => { e.stopPropagation(); togS(sid); }} style={{ width: 18, height: 18, borderRadius: 3, border: `2px solid ${dn ? P.success : P.dim}`, background: dn ? P.success : "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0, fontSize: 11, color: "#fff" }}>{dn && "\u2713"}</div>
          <div style={{ flex: 1, fontFamily: "Outfit", fontSize: 13, color: dn ? P.dim : P.text, textDecoration: dn ? "line-through" : "none" }}>{s.title}</div><Bd color={typeColor[s.type] || P.dim}>{s.type}</Bd></div>); })}
      </div>))}
    </div>))}
  </div>);

  const MonthV = () => { const m = CURRICULUM[selMonth]; if (!m) return null; return (<div style={{ padding: "24px", ...aS }}><Bk onClick={() => nav("curriculum")} label="All Months" />
    <div style={{ position: "relative", overflow: "hidden", background: m.color + "12", border: `1px solid ${m.color}33`, borderRadius: 16, padding: "28px 20px", marginBottom: 20 }}><IslamicPattern opacity={0.05} color={m.color} /><div style={{ position: "relative", zIndex: 1 }}><div style={{ fontSize: 36, marginBottom: 6 }}>{m.icon}</div><div style={{ fontFamily: "Outfit", fontSize: 11, fontWeight: 600, color: m.color, letterSpacing: 1.5, textTransform: "uppercase" }}>Month {m.month}</div><h2 style={{ fontFamily: "Amiri", fontSize: 26, color: P.text, margin: "4px 0" }}>{m.title}</h2><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: 0 }}>{m.subtitle}</p></div></div>
    {m.weeks.map(w => (<div key={w.week} style={{ marginBottom: 20 }}><h3 style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600, color: m.color, margin: "0 0 10px", display: "flex", alignItems: "center", gap: 8 }}><div style={{ width: 26, height: 26, borderRadius: 13, background: m.color + "22", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, color: m.color }}>{w.week}</div>{w.title}</h3>
      {w.sessions.map(s => { const sid = `${m.id}-w${w.week}-d${s.day}`; const dn = doneS[sid]; return (<div key={sid} onClick={() => nav("session", { month: selMonth, week: w.week, session: s })} style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 10, padding: "14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }} onMouseOver={e => { e.currentTarget.style.background = P.bgHover; }} onMouseOut={e => { e.currentTarget.style.background = P.bgCard; }}>
        <div onClick={e => { e.stopPropagation(); togS(sid); }} style={{ width: 22, height: 22, borderRadius: 5, border: `2px solid ${dn ? P.success : P.dim}`, background: dn ? P.success : "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0, fontSize: 12, color: "#fff", fontWeight: 700 }}>{dn && "\u2713"}</div>
        <div style={{ flex: 1 }}><div style={{ fontFamily: "Outfit", fontSize: 11, color: P.dim }}>Day {s.day}</div><div style={{ fontFamily: "Outfit", fontSize: 14, fontWeight: 500, color: P.text }}>{s.title}</div></div><Bd color={typeColor[s.type] || P.dim}>{s.type}</Bd><span style={{ color: P.dim }}>{"\u2192"}</span></div>); })}
    </div>))}
  </div>); };

  const SessV = () => { const m = CURRICULUM[selMonth]; if (!m || !selSession) return null; const s = selSession; const sid = `${m.id}-w${selWeek}-d${s.day}`; const dn = doneS[sid]; return (<div style={{ padding: "24px", maxWidth: 720, margin: "0 auto", ...aS }}>
    <Bk onClick={() => nav("month", { month: selMonth })} label={`Month ${m.month}`} />
    <div style={{ display: "flex", gap: 6, marginBottom: 8, flexWrap: "wrap" }}><Bd color={m.color}>Month {m.month}</Bd><Bd color={P.dim}>Week {selWeek}</Bd><Bd color={typeColor[s.type]}>{s.type}</Bd></div>
    <h2 style={{ fontFamily: "Amiri", fontSize: 26, color: P.text, margin: "8px 0 4px" }}>{s.title}</h2><p style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim, margin: "0 0 20px" }}>Day {s.day}</p>
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h3 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.gold, margin: "0 0 8px", textTransform: "uppercase" }}>{"\uD83D\uDCD6"} Lesson</h3><p style={{ fontFamily: "Outfit", fontSize: 14, color: P.text, lineHeight: 1.7, margin: 0 }}>{s.desc}</p></div>
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h3 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.tealL, margin: "0 0 10px", textTransform: "uppercase" }}>{"\uD83C\uDFAF"} Objectives</h3>{s.objectives?.map((o, i) => (<div key={i} style={{ display: "flex", gap: 8, marginBottom: 6 }}><div style={{ width: 20, height: 20, borderRadius: 10, background: P.teal + "22", color: P.tealL, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontWeight: 700, flexShrink: 0 }}>{i + 1}</div><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: 0, lineHeight: 1.5 }}>{o}</p></div>))}</div>
    {s.reading && <div style={{ background: P.gold + "0A", border: `1px solid ${P.gold}22`, borderRadius: 12, padding: "16px", marginBottom: 14 }}><h3 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.gold, margin: "0 0 4px" }}>{"\uD83D\uDCD5"} Reading</h3><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: 0 }}>{s.reading}</p></div>}
    {s.activity && <div style={{ background: P.emerald + "0A", border: `1px solid ${P.emerald}22`, borderRadius: 12, padding: "16px", marginBottom: 14 }}><h3 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.emerald, margin: "0 0 4px" }}>{"\uD83D\uDEE0"} Activity</h3><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: 0 }}>{s.activity}</p></div>}
    <button onClick={() => togS(sid)} style={{ width: "100%", padding: "13px", background: dn ? P.success + "22" : `linear-gradient(135deg, ${P.gold}, #B8962E)`, color: dn ? P.success : P.bg, border: dn ? `1px solid ${P.success}44` : "none", borderRadius: 10, fontFamily: "Outfit", fontSize: 14, fontWeight: 600, cursor: "pointer" }}>{dn ? "\u2713 Completed" : "Mark Complete \u2713"}</button>
  </div>); };

  const LabListV = () => (<div style={{ padding: "24px", ...aS }}>
    <div style={{ position: "relative", overflow: "hidden", background: `linear-gradient(135deg, #120820, #1a0830)`, border: `1px solid ${P.purple}33`, borderRadius: 16, padding: "28px 20px", marginBottom: 20, textAlign: "center" }}><IslamicPattern opacity={0.04} color={P.purple} /><div style={{ position: "relative", zIndex: 1 }}><div style={{ fontSize: 44, marginBottom: 6 }}>{"\uD83D\uDD2C"}</div><h2 style={{ fontFamily: "Amiri", fontSize: 28, color: P.text, margin: "0 0 4px" }}>Local AI Lab: Build Your Own {"\u02BF"}Ilm</h2><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: "0 0 14px" }}>Step-by-step guide to running AI privately on your machine</p><Br value={Object.keys(labD).length} max={LAB_STEPS.length} h={8} color={P.purple} /><div style={{ fontFamily: "Outfit", fontSize: 12, color: P.muted, marginTop: 4 }}>{Object.keys(labD).length}/{LAB_STEPS.length} steps</div></div></div>
    <div style={{ display: "grid", gap: 8 }}>{LAB_STEPS.map((step, i) => { const dn = labD[step.id]; return (<div key={step.id} onClick={() => nav("labstep", { labStep: i })} style={{ background: P.bgCard, border: `1px solid ${dn ? P.success + "44" : P.border}`, borderRadius: 10, padding: "14px 16px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }} onMouseOver={e => e.currentTarget.style.borderColor = dn ? P.success + "66" : P.purple + "44"} onMouseOut={e => e.currentTarget.style.borderColor = dn ? P.success + "44" : P.border}>
      <div style={{ width: 38, height: 38, borderRadius: 19, background: dn ? P.success + "22" : P.purple + "15", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, flexShrink: 0 }}>{dn ? "\u2705" : step.icon}</div><div style={{ flex: 1 }}><div style={{ fontFamily: "Outfit", fontSize: 11, color: P.dim }}>Step {step.id}</div><div style={{ fontFamily: "Outfit", fontSize: 14, fontWeight: 500, color: P.text }}>{step.title}</div></div><span style={{ color: P.dim }}>{"\u2192"}</span></div>); })}</div>
  </div>);

  const LabStepV = () => { const st = LAB_STEPS[labSt]; if (!st) return null; const dn = labD[st.id]; return (<div style={{ padding: "24px", maxWidth: 720, margin: "0 auto", ...aS }}>
    <Bk onClick={() => nav("lab")} label="All Steps" />
    <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}><Bd color={P.purple}>Lab</Bd><Bd color={P.cyan}>Step {st.id}/{LAB_STEPS.length}</Bd>{dn && <Bd color={P.success}>Done</Bd>}</div>
    <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}><span style={{ fontSize: 32 }}>{st.icon}</span><h2 style={{ fontFamily: "Amiri", fontSize: 26, color: P.text, margin: 0 }}>{st.title}</h2></div>
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "24px", marginBottom: 14 }}>{renderMd(st.content)}</div>
    {st.prereqs && <div style={{ background: P.warn + "0A", border: `1px solid ${P.warn}22`, borderRadius: 12, padding: "16px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.warn, margin: "0 0 8px" }}>{"\uD83D\uDCCB"} Prerequisites</h4>{st.prereqs.map((p, i) => <div key={i} style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, marginBottom: 4 }}>{"\u2022"} {p}</div>)}</div>}
    {st.commands && <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.tealL, margin: "0 0 12px" }}>{"\uD83D\uDCBB"} Installation</h4>{st.commands.map((c, i) => (<div key={i} style={{ marginBottom: 16 }}><div style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.cyan, marginBottom: 6 }}>{"\uD83D\uDDA5\uFE0F"} {c.platform}</div>{c.steps.map((s, j) => <div key={j} style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, marginBottom: 3, paddingLeft: 12 }}>{j + 1}. {s}</div>)}</div>))}{st.verify && <><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.success, margin: "12px 0 4px" }}>{"\u2705"} Verify</h4><CB>{st.verify}</CB><p style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim }}>{st.verifyDesc}</p></>}</div>}
    {st.mainCommand && <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.tealL, margin: "0 0 6px" }}>{"\uD83D\uDCBB"} Command</h4><CB>{st.mainCommand}</CB><p style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim, margin: "4px 0 0" }}>{st.mainCommandDesc}</p></div>}
    {st.altCommands && <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.muted, margin: "0 0 8px" }}>{"\uD83D\uDD00"} More Commands</h4>{st.altCommands.map((c, i) => <div key={i} style={{ marginBottom: 10 }}><CB>{c.cmd}</CB><p style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim, margin: 0 }}>{c.desc}</p></div>)}</div>}
    {st.examplePrompts && <div style={{ background: P.purple + "0A", border: `1px solid ${P.purple}22`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.purple, margin: "0 0 10px" }}>{"\uD83D\uDDE3\uFE0F"} Try These Prompts</h4>{st.examplePrompts.map((p, i) => (<div key={i} style={{ background: "#000", borderRadius: 8, padding: "10px 14px", marginBottom: 8 }}><div style={{ fontFamily: "monospace", fontSize: 13, color: "#4ADE80" }}>{">"} {p.prompt}</div><div style={{ fontFamily: "Outfit", fontSize: 11, color: P.dim, marginTop: 4 }}>Purpose: {p.purpose}</div></div>))}{st.exitCommand && <div style={{ marginTop: 8 }}><CB>{st.exitCommand}</CB><p style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim }}>{st.exitDesc}</p></div>}</div>}
    {st.customization && <div style={{ background: P.gold + "0A", border: `1px solid ${P.gold}22`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.gold, margin: "0 0 8px" }}>{"\u2728"} Customize</h4>{renderMd(st.customization)}</div>}
    {st.configExample && <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.cyan, margin: "0 0 8px" }}>{"\uD83D\uDCDD"} Modelfile</h4><CB>{st.configExample}</CB></div>}
    {st.activity && <div style={{ background: P.emerald + "0A", border: `1px solid ${P.emerald}22`, borderRadius: 12, padding: "16px", marginBottom: 14 }}><h4 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.emerald, margin: "0 0 4px" }}>{"\uD83D\uDEE0"} Activity</h4><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: 0 }}>{st.activity}</p></div>}
    {st.isGraduation && <div style={{ background: `linear-gradient(135deg, ${P.gold}12, ${P.purple}12)`, border: `1px solid ${P.gold}33`, borderRadius: 12, padding: "24px", marginBottom: 14, textAlign: "center" }}><div style={{ fontSize: 48, marginBottom: 8 }}>{"\uD83C\uDF93"}</div><div style={{ fontFamily: "Amiri", fontSize: 22, color: P.gold }}>MashaAllah {"\u2014"} Lab Complete!</div><ArabicOrnament /></div>}
    <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
      {labSt > 0 && <button onClick={() => nav("labstep", { labStep: labSt - 1 })} style={{ flex: 1, padding: "12px", background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 10, color: P.muted, fontFamily: "Outfit", fontSize: 13, cursor: "pointer" }}>{"\u2190"} Previous</button>}
      <button onClick={() => { setLabD(p => ({ ...p, [st.id]: true })); if (labSt < LAB_STEPS.length - 1) nav("labstep", { labStep: labSt + 1 }); else nav("lab"); }} style={{ flex: 2, padding: "12px", background: dn ? P.success + "22" : `linear-gradient(135deg, ${P.purple}, #7C3AED)`, color: dn ? P.success : "#fff", border: dn ? `1px solid ${P.success}44` : "none", borderRadius: 10, fontFamily: "Outfit", fontSize: 14, fontWeight: 600, cursor: "pointer" }}>{dn ? "\u2713 Done" : labSt < LAB_STEPS.length - 1 ? "Complete & Next \u2192" : "Complete Lab \uD83C\uDF93"}</button>
    </div>
  </div>); };

  const CtfListV = () => (<div style={{ padding: "24px", ...aS }}>
    <div style={{ position: "relative", overflow: "hidden", background: `linear-gradient(135deg, #1A0505, #2A1010)`, border: `1px solid ${P.danger}33`, borderRadius: 16, padding: "28px 20px", marginBottom: 20, textAlign: "center" }}><IslamicPattern opacity={0.05} color={P.danger} /><div style={{ position: "relative", zIndex: 1 }}><div style={{ fontSize: 44, marginBottom: 6 }}>{"\uD83D\uDEA9"}</div><h2 style={{ fontFamily: "Amiri", fontSize: 28, color: P.text, margin: "0 0 4px" }}>AI Capture the Flag</h2><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: "0 0 14px" }}>Hands-on challenges inspired by Islamic scholars</p><div style={{ display: "flex", gap: 20, justifyContent: "center" }}><div><div style={{ fontFamily: "Outfit", fontSize: 26, fontWeight: 700, color: P.gold }}>{ctfScore}</div><div style={{ fontSize: 10, color: P.dim }}>Points</div></div><div style={{ width: 1, background: P.border }} /><div><div style={{ fontFamily: "Outfit", fontSize: 26, fontWeight: 700, color: P.tealL }}>{Object.keys(doneCh).length}/{CTF_CHALLENGES.length}</div><div style={{ fontSize: 10, color: P.dim }}>Solved</div></div></div></div></div>
    <div style={{ display: "grid", gap: 8 }}>{CTF_CHALLENGES.map(ch => { const sv = doneCh[ch.id]; return (<div key={ch.id} onClick={() => nav("challenge", { challenge: ch.id })} style={{ background: P.bgCard, border: `1px solid ${sv ? P.success + "44" : P.border}`, borderRadius: 10, padding: "14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }} onMouseOver={e => e.currentTarget.style.borderColor = sv ? P.success + "66" : P.gold + "44"} onMouseOut={e => e.currentTarget.style.borderColor = sv ? P.success + "44" : P.border}>
      <div style={{ width: 36, height: 36, borderRadius: 8, background: sv ? P.success + "22" : P.border, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, flexShrink: 0 }}>{sv ? "\u2705" : "\uD83D\uDD12"}</div><div style={{ flex: 1 }}><div style={{ fontFamily: "Outfit", fontSize: 14, fontWeight: 500, color: P.text }}>{ch.title}</div><div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 3 }}><Bd color={catCol[ch.category] || P.dim}>{ch.category}</Bd><span style={{ fontSize: 11, color: P.dim }}>{Array(3).fill(0).map((_, i) => <span key={i} style={{ color: i < ch.difficulty ? P.gold : P.dim }}>{"\u2605"}</span>)}</span></div></div><div style={{ textAlign: "right", flexShrink: 0 }}><div style={{ fontFamily: "Outfit", fontSize: 17, fontWeight: 700, color: sv ? P.success : P.gold }}>{ch.points}</div><div style={{ fontSize: 9, color: P.dim }}>PTS</div></div></div>); })}</div>
  </div>);

  const ChV = () => { const ch = CTF_CHALLENGES.find(c => c.id === selCh); if (!ch) return null; const sv = doneCh[ch.id]; return (<div style={{ padding: "24px", maxWidth: 720, margin: "0 auto", ...aS }}>
    <Bk onClick={() => nav("ctf")} label="Challenges" />
    <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 8 }}><Bd color={P.danger}>CTF</Bd><Bd color={catCol[ch.category] || P.dim}>{ch.category}</Bd><span style={{ fontFamily: "Outfit", fontSize: 14, fontWeight: 700, color: P.gold, marginLeft: "auto" }}>{ch.points} pts</span></div>
    <h2 style={{ fontFamily: "Amiri", fontSize: 24, color: P.text, margin: "8px 0 16px" }}>{ch.title}</h2>
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginBottom: 14, fontFamily: "monospace", whiteSpace: "pre-wrap", fontSize: 13, color: P.text, lineHeight: 1.7 }}>{ch.description}</div>
    {!sv && <button onClick={() => setHint(!hint)} style={{ background: "none", border: `1px solid ${P.warn}33`, borderRadius: 8, padding: "9px 14px", color: P.warn, fontFamily: "Outfit", fontSize: 12, cursor: "pointer", marginBottom: 14, width: "100%" }}>{hint ? "\uD83D\uDD13 Hide Hint" : "\uD83D\uDCA1 Hint"}</button>}
    {hint && !sv && <div style={{ background: P.warn + "0A", border: `1px solid ${P.warn}22`, borderRadius: 10, padding: "14px", marginBottom: 14 }}><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.warn, margin: 0 }}>{"\uD83D\uDCA1"} {ch.hint}</p></div>}
    {!sv ? (<div style={{ marginBottom: 14 }}><div style={{ display: "flex", gap: 8 }}><input type="text" value={ctfIn} onChange={e => { setCtfIn(e.target.value); setCtfRes(null); }} onKeyDown={e => e.key === "Enter" && subFlag()} placeholder="FLAG{your_answer}" style={{ flex: 1, padding: "11px 14px", background: P.bg, border: `1px solid ${ctfRes === "no" ? P.danger : P.border}`, borderRadius: 8, color: P.text, fontFamily: "monospace", fontSize: 14, outline: "none" }} /><button onClick={subFlag} style={{ padding: "11px 20px", background: `linear-gradient(135deg, ${P.gold}, #B8962E)`, color: P.bg, border: "none", borderRadius: 8, fontFamily: "Outfit", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>Submit {"\uD83D\uDEA9"}</button></div>{ctfRes === "no" && <div style={{ fontFamily: "Outfit", fontSize: 12, color: P.danger, marginTop: 6 }}>{"\u274C"} Incorrect.</div>}</div>)
    : (<div style={{ background: P.success + "12", border: `1px solid ${P.success}33`, borderRadius: 12, padding: "20px", marginBottom: 14, textAlign: "center" }}><div style={{ fontSize: 36, marginBottom: 6 }}>{"\uD83C\uDF89"}</div><div style={{ fontFamily: "Outfit", fontSize: 16, fontWeight: 600, color: P.success }}>Solved!</div><div style={{ fontFamily: "monospace", fontSize: 15, color: P.gold, margin: "4px 0 8px" }}>{ch.flag}</div><div style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.gold }}>+{ch.points} pts</div></div>)}
    {sv && <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "18px" }}><h3 style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 600, color: P.tealL, margin: "0 0 6px" }}>{"\uD83D\uDCD8"} Explanation</h3><p style={{ fontFamily: "Outfit", fontSize: 13, color: P.muted, margin: 0, lineHeight: 1.6 }}>{ch.explanation}</p></div>}
  </div>); };

  const ProgV = () => (<div style={{ padding: "24px", ...aS }}><h2 style={{ fontFamily: "Amiri", fontSize: 26, color: P.text, margin: "0 0 20px" }}>Your Progress</h2>
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "24px", marginBottom: 14, textAlign: "center" }}><div style={{ width: 90, height: 90, borderRadius: 45, border: `4px solid ${P.gold}`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 10px", background: P.gold + "0A" }}><span style={{ fontFamily: "Outfit", fontSize: 28, fontWeight: 700, color: P.gold }}>{pct}%</span></div><div style={{ fontFamily: "Outfit", fontSize: 15, color: P.text }}>Course Progress</div><div style={{ fontFamily: "Outfit", fontSize: 12, color: P.dim, marginBottom: 8 }}>{dC}/{totS} sessions</div><Br value={dC} max={totS} h={10} /></div>
    {CURRICULUM.map(m => { const ms = m.weeks.reduce((t, w) => t + w.sessions.length, 0); const md = m.weeks.reduce((t, w) => t + w.sessions.filter(s => doneS[`${m.id}-w${w.week}-d${s.day}`]).length, 0); return <div key={m.id} style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 10, padding: "14px", marginBottom: 6, display: "flex", alignItems: "center", gap: 12 }}><span style={{ fontSize: 24 }}>{m.icon}</span><div style={{ flex: 1 }}><div style={{ fontFamily: "Outfit", fontSize: 13, fontWeight: 500, color: P.text }}>{m.title}</div><Br value={md} max={ms} h={5} color={m.color} /><div style={{ fontFamily: "Outfit", fontSize: 11, color: P.dim, marginTop: 2 }}>{md}/{ms}</div></div></div>; })}
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginTop: 14 }}><h3 style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600, color: P.purple, margin: "0 0 10px" }}>{"\uD83D\uDD2C"} Lab</h3><Br value={Object.keys(labD).length} max={LAB_STEPS.length} h={8} color={P.purple} /><div style={{ fontFamily: "Outfit", fontSize: 12, color: P.muted, marginTop: 4 }}>{Object.keys(labD).length}/{LAB_STEPS.length} steps</div></div>
    <div style={{ background: P.bgCard, border: `1px solid ${P.border}`, borderRadius: 12, padding: "20px", marginTop: 10 }}><h3 style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600, color: P.danger, margin: "0 0 10px" }}>{"\uD83D\uDEA9"} CTF</h3><div style={{ display: "flex", gap: 20, marginBottom: 10 }}><div><div style={{ fontFamily: "Outfit", fontSize: 22, fontWeight: 700, color: P.gold }}>{ctfScore}/{totPts}</div><div style={{ fontSize: 10, color: P.dim }}>Points</div></div><div><div style={{ fontFamily: "Outfit", fontSize: 22, fontWeight: 700, color: P.tealL }}>{Object.keys(doneCh).length}/{CTF_CHALLENGES.length}</div><div style={{ fontSize: 10, color: P.dim }}>Solved</div></div></div><Br value={Object.keys(doneCh).length} max={CTF_CHALLENGES.length} h={8} color={P.danger} /></div>
  </div>);

  return (<div style={{ fontFamily: "Outfit, sans-serif", background: P.bg, color: P.text, minHeight: "100vh", maxWidth: 900, margin: "0 auto", position: "relative" }}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=Outfit:wght@300;400;500;600;700;800&display=swap');* { box-sizing: border-box; margin: 0; padding: 0; } body { background: ${P.bg}; margin: 0; } ::-webkit-scrollbar { width: 6px; } ::-webkit-scrollbar-track { background: ${P.bg}; } ::-webkit-scrollbar-thumb { background: ${P.border}; border-radius: 3px; } input::placeholder { color: ${P.dim}; }`}</style>
    {sb && <div onClick={() => setSb(false)} style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 999 }} />}
    <Sidebar /><Header />
    {view === "home" && <Home />}
    {view === "curriculum" && <CurrV />}
    {view === "month" && <MonthV />}
    {view === "session" && <SessV />}
    {view === "ctf" && <CtfListV />}
    {view === "challenge" && <ChV />}
    {view === "lab" && <LabListV />}
    {view === "labstep" && <LabStepV />}
    {view === "progress" && <ProgV />}
    <footer style={{ padding: "28px 24px", textAlign: "center", borderTop: `1px solid ${P.border}`, marginTop: 28 }}>
      <div style={{ fontFamily: "Amiri", fontSize: 18, color: P.gold, marginBottom: 4 }}>{"\u0631\u064E\u0628\u0651\u0650 \u0632\u0650\u062F\u0652\u0646\u0650\u064A \u0639\u0650\u0644\u0652\u0645\u064B\u0627"}</div>
      <div style={{ fontFamily: "Outfit", fontSize: 11, color: P.dim, fontStyle: "italic" }}>"My Lord, increase me in knowledge." {"\u2014"} Quran 20:114</div>
      <ArabicOrnament />
      <div style={{ fontFamily: "Outfit", fontSize: 10, color: P.dim }}>AI and Islamic Ethics {"\u00B7"} Guardians of the Digital Amanah</div>
    </footer>
  </div>);
}
